# Generated by Django 5.0.2 on 2024-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
